//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysMecanicaApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/SysMecanica")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double preco {
            get {
                return this.precoField;
            }
            set {
                if ((this.precoField.Equals(value) != true)) {
                    this.precoField = value;
                    this.RaisePropertyChanged("preco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProdutoService")]
    public interface IProdutoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Adicionar", ReplyAction="http://tempuri.org/IProdutoService/AdicionarResponse")]
        void Adicionar(SysMecanicaApp.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Adicionar", ReplyAction="http://tempuri.org/IProdutoService/AdicionarResponse")]
        System.Threading.Tasks.Task AdicionarAsync(SysMecanicaApp.ServiceReference1.Produto p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Buscar", ReplyAction="http://tempuri.org/IProdutoService/BuscarResponse")]
        SysMecanicaApp.ServiceReference1.Produto Buscar(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/Buscar", ReplyAction="http://tempuri.org/IProdutoService/BuscarResponse")]
        System.Threading.Tasks.Task<SysMecanicaApp.ServiceReference1.Produto> BuscarAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutoServiceChannel : SysMecanicaApp.ServiceReference1.IProdutoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoServiceClient : System.ServiceModel.ClientBase<SysMecanicaApp.ServiceReference1.IProdutoService>, SysMecanicaApp.ServiceReference1.IProdutoService {
        
        public ProdutoServiceClient() {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Adicionar(SysMecanicaApp.ServiceReference1.Produto p) {
            base.Channel.Adicionar(p);
        }
        
        public System.Threading.Tasks.Task AdicionarAsync(SysMecanicaApp.ServiceReference1.Produto p) {
            return base.Channel.AdicionarAsync(p);
        }
        
        public SysMecanicaApp.ServiceReference1.Produto Buscar(int codigo) {
            return base.Channel.Buscar(codigo);
        }
        
        public System.Threading.Tasks.Task<SysMecanicaApp.ServiceReference1.Produto> BuscarAsync(int codigo) {
            return base.Channel.BuscarAsync(codigo);
        }
    }
}
